"""Scan `assets/sounds/` and emit a manifest of available files.

Users drop their own audio files into the categorized folders (see
`assets/sounds/README.md`). The runtime randomly picks from what's available
in each category. The manifest is emitted as `assets/js/sounds.js`.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOUNDS_DIR = REPO_ROOT / "assets" / "sounds"
OUTPUT_FILE = REPO_ROOT / "assets" / "js" / "sounds.js"

AUDIO_EXTENSIONS = {".mp3", ".ogg", ".wav", ".m4a", ".webm"}

# Categories the runtime knows about. Adding a directory here makes it
# scannable; the JS side decides how to use it.
CATEGORIES = [
    "bark",
    "whine",
    "happy",
    "eating",
    "music/idle",
    "music/play",
    "music/sleep",
]


def scan_category(sounds_dir: Path, category: str) -> list[str]:
    """Return relative paths for all audio files in a category, sorted."""
    cat_dir = sounds_dir / category
    if not cat_dir.exists():
        return []
    files = [
        p.relative_to(sounds_dir.parent).as_posix()
        for p in cat_dir.iterdir()
        if p.is_file() and p.suffix.lower() in AUDIO_EXTENSIONS
    ]
    return sorted(files)


def build_manifest(sounds_dir: Path = SOUNDS_DIR) -> dict[str, list[str]]:
    return {cat: scan_category(sounds_dir, cat) for cat in CATEGORIES}


def render_js(manifest: dict[str, list[str]]) -> str:
    payload = json.dumps(manifest, indent=2, ensure_ascii=False)
    return (
        "// AUTOGENERATED by scripts/build_sounds.py — do not edit by hand.\n"
        "// Add audio files under assets/sounds/<category>/ and rebuild.\n"
        f"export const SOUND_MANIFEST = Object.freeze({payload});\n"
        "export default SOUND_MANIFEST;\n"
    )


def build(
    sounds_dir: Path = SOUNDS_DIR, output: Path = OUTPUT_FILE
) -> Path:
    manifest = build_manifest(sounds_dir)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_js(manifest), encoding="utf-8")
    return output


def main() -> int:
    out = build()
    manifest = build_manifest()
    total = sum(len(v) for v in manifest.values())
    print(f"build_sounds: wrote {out.relative_to(REPO_ROOT)} ({total} files indexed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
