"""Compile `_data/*.yml` into a single ES module at `assets/js/data.js`.

The generated file exports a frozen `DOGGO_DATA` constant containing all
breed, personality, accessory, and color catalog data for the runtime.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "_data"
OUTPUT_FILE = REPO_ROOT / "assets" / "js" / "data.js"

EXPECTED_FILES = {
    "breeds": "breeds.yml",
    "personalities": "personalities.yml",
    "accessories": "accessories.yml",
    "colors": "colors.yml",
}


def load_yaml(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_all(data_dir: Path) -> dict[str, Any]:
    """Load every expected YAML file, raising FileNotFoundError if any are missing."""
    loaded: dict[str, Any] = {}
    for key, filename in EXPECTED_FILES.items():
        path = data_dir / filename
        if not path.exists():
            raise FileNotFoundError(f"missing data file: {path}")
        loaded[key] = load_yaml(path)
    return loaded


def validate(data: dict[str, Any]) -> list[str]:
    """Return a list of validation errors (empty if valid)."""
    errors: list[str] = []

    breeds = data.get("breeds")
    if not isinstance(breeds, list) or not breeds:
        errors.append("breeds.yml must contain a non-empty list")
    else:
        ids = [b.get("id") for b in breeds]
        if len(ids) != len(set(ids)):
            errors.append("breeds.yml contains duplicate ids")
        for b in breeds:
            for required in ("id", "name", "body_type"):
                if required not in b:
                    errors.append(f"breed {b.get('id', '?')} missing {required}")

    personalities = data.get("personalities")
    if not isinstance(personalities, list) or not personalities:
        errors.append("personalities.yml must contain a non-empty list")
    else:
        for p in personalities:
            if "decay" not in p:
                errors.append(f"personality {p.get('id', '?')} missing decay")
                continue
            for stat in ("hunger", "thirst", "bladder", "energy"):
                if stat not in p["decay"]:
                    errors.append(
                        f"personality {p.get('id', '?')} missing decay.{stat}"
                    )

    accessories = data.get("accessories")
    if not isinstance(accessories, dict):
        errors.append("accessories.yml must be a mapping")
    else:
        for slot in ("collars", "clothes", "tricks"):
            if slot not in accessories:
                errors.append(f"accessories.yml missing {slot}")

    colors = data.get("colors")
    if not isinstance(colors, dict):
        errors.append("colors.yml must be a mapping")
    else:
        for key in ("coat_colors", "markings", "eye_colors"):
            if key not in colors:
                errors.append(f"colors.yml missing {key}")

    return errors


def render_js(data: dict[str, Any]) -> str:
    """Render an ES module exporting a frozen data object."""
    payload = json.dumps(data, indent=2, ensure_ascii=False, sort_keys=False)
    return (
        "// AUTOGENERATED by scripts/build_data.py — do not edit by hand.\n"
        "// Source: _data/*.yml\n"
        f"export const DOGGO_DATA = Object.freeze({payload});\n"
        "export default DOGGO_DATA;\n"
    )


def build(data_dir: Path = DATA_DIR, output: Path = OUTPUT_FILE) -> Path:
    """Run the full build. Returns the output path."""
    data = load_all(data_dir)
    errors = validate(data)
    if errors:
        msg = "\n".join(f"  - {e}" for e in errors)
        raise ValueError(f"data validation failed:\n{msg}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_js(data), encoding="utf-8")
    return output


def main() -> int:
    try:
        out = build()
    except (FileNotFoundError, ValueError) as e:
        print(f"build_data: {e}")
        return 1
    print(f"build_data: wrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
